<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseIntermediateOutputPath>obj\game\</BaseIntermediateOutputPath>
    <BaseOutputPath>bin\game\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests/**/*.cs" />
    <Compile Remove="obj/**/*.cs" />
    <Compile Remove="bin/**/*.cs" />
  </ItemGroup>

</Project>
